branches:
  only:
    - travis-ci-sandbox

install:
  - gem install asciidoctor
  - sudo pip install Pygments
  - sudo pip install -r scripts/requirements.txt
  - cd scripts
  - cd ..
  - rm -rf public || exit 0

script:
  - ./bin/hugo --buildFuture --verbose
  - cd public
  - touch .nojekyll
  - echo "redhatgov.rhtdemo.com" > CNAME
  - ls -lah

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: travis-ci-sandbox
